# SeaweedFS S3 credentials
# Change these values for production use.
apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs-creds
type: Opaque
stringData:
  access-key: "saiyan-trainer"
  secret-key: "saiyan-trainer-secret"
